data_dir: /lustre/fsn1/projects/rech/ego/uyr48jk/alphaearth_embeddings/2018
satellite_default:
  resolution: 10
  tile_size: 10240
  dtype: Float32
  composite_method: MOSAIC
  aoi:
    country: France
    spatial:
      left: 12550
      right: 1118000
      bottom: 6050000
      top: 7163000
      epsg: 2154
    temporal:
      start_date: '2018-01-01'
      end_date: '2018-12-31'
  gee:
    ee_project_id: phdforest
    max_tile_size: 8
customs:
  alphaearth_embeddings:
    url: GOOGLE/SATELLITE/EMBEDDING/V1/ANNUAL
    pixel_range:
      - -1
      - 1
    selected_bands:
      - A00
      - A01
      - A02
      - A03
      - A04
      - A05
      - A06
      - A07
      - A08
      - A09
      - A10
      - A11
      - A12
      - A13
      - A14
      - A15
      - A16
      - A17
      - A18
      - A19
      - A20
      - A21
      - A22
      - A23
      - A24
      - A25
      - A26
      - A27
      - A28
      - A29
      - A30
      - A31
      - A32
      - A33
      - A34
      - A35
      - A36
      - A37
      - A38
      - A39
      - A40
      - A41
      - A42
      - A43
      - A44
      - A45
      - A46
      - A47
      - A48
      - A49
      - A50
      - A51
      - A52
      - A53
      - A54
      - A55
      - A56
      - A57
      - A58
      - A59
      - A60
      - A61
      - A62
      - A63
    composite_method: MOSAIC
    dtype: Float32
    aoi:
      temporal:
        start_date: '2018-01-01'
        end_date: '2018-12-31'
